### ISSUE TITLE
Assertion `face != nullptr' failed

### ISSUE THREAD

**Issue by tianxiaogu** [freetype/freetype2-testing#60]
Our fuzzing tool has found a test case that leads the **fuzzing driver** to crash.
We have followed the steps described in <https://github.com/libarchive/libarchive/issues/1058#issuecomment-418651262> to reproduce this issue.

[cff-test-case.zip](https://github.com/freetype/freetype2-testing/files/2364830/cff-test-case.zip)

```
../build/bin/driver --cff cff-test-case
driver: freetype2-testing/fuzzing/src/visitors/facevisitor-charcodes.cpp:52: virtual void FaceVisitorCharCodes::run(fuzzing::Unique_FT_Face): Assertion `face != nullptr' failed.
Aborted
```
The `abort` can also be reproduced with `--cff-ftengine`.
Hope this report is helpful.

**Comment by cherusker** [comment]
Hi @tianxiaogu, thank you a lot for your report :) This issue can actually be traced back to `freetype2` itself and we're already working on/discussing a fix for that -- the fix should be live soon.

**Comment by cherusker** [comment]
Fixed now in `freetype2`'s git: http://git.savannah.gnu.org/cgit/freetype/freetype2.git/commit/?id=642bc7590c701c8cd35a9f60fa899cfa518b17ff

Feel free to report more if you find anything :)
